name: MR Checks

on: [ pull_request ]

jobs:
  python-check:
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.10", "3.11"]
        exclude:
          - os: macos-latest
            python-version: '3.8'
          - os: ubuntu-latest
            python-version: '3.8'
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml
            **/requirements*.txt
      # Cache Poetry dependencies
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-
      # Cache nox environments
      - name: Cache nox environments
        uses: actions/cache@v4
        with:
          path: .nox
          key: ${{ runner.os }}-nox-${{ matrix.python-version }}-${{ hashFiles('**/noxfile.py') }}
          restore-keys: |
            ${{ runner.os }}-nox-${{ matrix.python-version }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uvx poetry lock
          uvx poetry install
      - name: Lint
        run: |
          uvx nox -s lint
      - name: Test
        run: |
          uvx nox -s pytest
      # Only run on Windows since Photoshop is Windows-only
      - name: Test with Photoshop (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          uvx nox -s test-photoshop
        continue-on-error: true  # Photoshop tests may fail if Photoshop is not installed
